spring:
  application:
    name: swiggy-authService
  datasource:
     url: jdbc:mysql://localhost:3306/swiggy_db_authServiceDB?createDatabaseIfNotExist=true
     username: root
     password: root
  jpa:
    show-sql: true
    hibernate: 
        ddl-auto: update
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
FRONTEND_URL: http:localhost:5173/
